#if !canImport(ObjectiveC)
import XCTest

extension LogDogChalkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LogDogChalkTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LogDogChalkTests.__allTests__LogDogChalkTests),
    ]
}
#endif
